active_address: "0xccf281e7d5a183ff4b63339a4da42220f30653f46e475463e997793f80b56ea3"
active_env: "testnet"
keystore:
  File: "C:\\Users\\TheCe\\.sui\\sui_config\\sui.keystore"
envs:
  - alias: "testnet"
    rpc: "https://fullnode.testnet.sui.io:443"
    ws: "wss://fullnode.testnet.sui.io:443"

